name: Rust
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fmt
        run: cargo fmt -- --check
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: make test
      - name: Build
        run: cargo build --verbose
      - name: Integration tests
        run: make builder redis-server-d test-integration stop-redis-server
      - name: Integration tests (redis cluster)
        run: make builder redis-cluster-d test-cluster-integration stop-redis-cluster
